#=================================================
#   Description: Build X-Wrt using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: build-x-wrt-6.0_b201911290805

on: 
  release:
    types: [published]
  push:
    branches:
      - master
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone source code
      run: git clone --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git

    - name: Building
      run: |
        cp *.sh x-wrt/
        cp release.tag x-wrt/
        cd x-wrt
        echo -e "$(nproc) thread build."
        sh build.sh $(nproc)

