#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: Build Jobs 21.10_b202112171543-rebuild-part

on:
  push:
    tags:
    - 'v*'

jobs:
  build-ath79-generic_ath79-generic-nosymbol_ath79-nand:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      run: git clone --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git
    - name: Update feeds
      run: cd x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh x-wrt/
        cp release.tag x-wrt/
        cd x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ath79-generic ath79-generic-nosymbol ath79-nand" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@main
      if: failure()
      with:
        name: build-failure-log-ath79-generic_ath79-generic-nosymbol_ath79-nand
        path: make.log
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value="https://uploads.github.com/repos/x-wrt/build-release/releases/55521268/assets{?name,label}"
        echo ::set-output name=upload_url::$value
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-21.10_b202112171543-ath79-generic
      id: asset-f8bad5254534d618191b2e0143548a97
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./x-wrt/x-wrt-21.10_b202112171543-ath79-generic.zip
        asset_name: x-wrt-21.10_b202112171543-ath79-generic.zip
        asset_content_type: application/zip
    - name: Upload Release Asset x-wrt-21.10_b202112171543-ath79-generic-nosymbol
      id: asset-6e206e742a5da255227924412e43ad56
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./x-wrt/x-wrt-21.10_b202112171543-ath79-generic-nosymbol.zip
        asset_name: x-wrt-21.10_b202112171543-ath79-generic-nosymbol.zip
        asset_content_type: application/zip
    - name: Upload Release Asset x-wrt-21.10_b202112171543-ath79-nand
      id: asset-f89d4bb2cbb3722aa826ee3145cfb773
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./x-wrt/x-wrt-21.10_b202112171543-ath79-nand.zip
        asset_name: x-wrt-21.10_b202112171543-ath79-nand.zip
        asset_content_type: application/zip
